### ISSUE TITLE
Meslo LG L Regular and LG M Regular are broken

### ISSUE THREAD

**Issue by ericbn** [halyard/font-meslo-powerline#2]
LG S Regular is okay. Didn't check the DZ ones.

And all characters are blank in iTerm. And this is all I get in Mac Font Book:

<img width="621" alt="screen shot 2016-11-04 at 11 51 40 am" src="https://cloud.githubusercontent.com/assets/4120606/20014489/3b94355e-a285-11e6-97ac-b76c5d152ae2.png">

**Comment by akerl** [comment]
![image](https://cloud.githubusercontent.com/assets/491209/20015599/4898ddce-a279-11e6-975e-4a4281e46e7c.png)

![image](https://cloud.githubusercontent.com/assets/491209/20015602/4d2901c0-a279-11e6-8ac9-dc6cb0474d25.png)

Just re-installed mine and wasn't able to replicate. What version of OSX are you on?

**Comment by ericbn** [comment]
I'm using 10.11.6. Just removed the fonts, restarted the computer, installed them again, and it's working now! (just removing and installing again didn't work) 😓 

Thanks for the answer.
